let cal_lang = [
  "af", "Kalender";
  "am", "የቀን አቆጣጠር";
  "ar", "التقويم";
  "ast", "calendariu";
  "as", "কেলেণ্ডাৰ";
  "az", "Təqvim";
  "be", "каляндар";
  "bg", "календар";
  "bn", "ক্যালেন্ডার";
  "br", "deiziadur";
  "brx", "पंचाग";
  "bs", "Kalendar";
  "bs_Cyrl", "Календар";
  "ca", "calendari";
  "ccp", "𑄇𑄳𑄠𑄣𑄬𑄚𑄴𑄓𑄢𑄴";
  "ce", "Календарь";
  "chr", "ᏅᏙ ᏗᏎᏍᏗ";
  "cs", "Kalendář";
  "cy", "Calendr";
  "da", "kalender";
  "de", "Kalender";
  "dsb", "kalender";
  "dz", "ཟླ་ཐོ";
  "ee", "kalenda";
  "el", "Ημερολόγιο";
  "en", "Calendar";
  "es", "calendario";
  "et", "kalender";
  "eu", "Egutegia";
  "fa", "تقویم";
  "ff_Adlm", "𞤙𞤢𞤤𞤯𞤭𞤥𞤫𞤪𞤫";
  "fil", "Kalendaryo";
  "fi", "kalenteri";
  "fo", "kalendari";
  "fr", "calendrier";
  "ga", "Féilire";
  "gd", "Mìosachan";
  "gl", "calendario";
  "gsw", "Kaländer";
  "gu", "કેલેન્ડર";
  "ha", "Kalanda";
  "he", "לוח שנה";
  "hi", "कैलेंडर";
  "hr", "kalendar";
  "hsb", "protyka";
  "hu", "Naptár";
  "hy", "օրացույց";
  "ia", "calendario";
  "id", "Kalender";
  "ig", "Kalịnda";
  "is", "Tímatal";
  "it", "Calendario";
  "ja", "暦法";
  "jv", "Tanggalan";
  "ka", "კალენდარი";
  "kea", "Kalendáriu";
  "kk", "Күнтізбе";
  "km", "ប្រតិទិន";
  "kn", "ಕ್ಯಾಲೆಂಡರ್";
  "kok", "दिनदर्शिका";
  "ko", "달력";
  "ks", "کیلنڑر";
  "ku", "salname";
  "ky", "Жылнаама";
  "lb", "Kalenner";
  "lo", "ປະຕິທິນ";
  "lt", "kalendorius";
  "lv", "Kalendārs";
  "mk", "Календар";
  "ml", "കലണ്ടർ";
  "mn", "цаглавар";
  "mr", "दिनदर्शिका";
  "ms", "Kalendar";
  "mt", "Kalendarju";
  "my", "ပြက္ခဒိန်";
  "nb", "kalender";
  "ne", "पात्रो";
  "nl", "kalender";
  "nnh", "fʉ̀ʼ njÿó";
  "nn", "kalender";
  "or", "କ୍ୟାଲେଣ୍ଡର୍";
  "pa", "ਕੈਲੰਡਰ";
  "pcm", "Kalẹ́nda";
  "pl", "kalendarz";
  "ps", "جنتري";
  "pt", "Calendário";
  "qu", "Intiwatana";
  "ro", "tip calendar";
  "ru", "календарь";
  "sah", "Халандаар";
  "sd", "ڪئلينڊر";
  "si", "දින දර්ශනය";
  "sk", "kalendár";
  "sl", "koledar";
  "so", "Habeentiris";
  "sq", "Kalendari";
  "sr", "календар";
  "sr_Latn", "kalendar";
  "sv", "kalender";
  "sw", "Kalenda";
  "ta", "நாள்காட்டி";
  "te", "క్యాలెండర్";
  "th", "ปฏิทิน";
  "tk", "Senenama";
  "to", "tohi māhina";
  "tr", "Takvim";
  "uk", "календар";
  "ur", "کیلنڈر";
  "uz", "taqvim";
  "vi", "Lịch";
  "yo", "Kàlẹ́ńdà";
  "yue", "曆法";
  "zgh", "ⴰⵙⵎⵍⵓⵙⵙⴰⵏ";
  "zh", "日历";
  "zu", "Ikhalenda";
]
