let lang_words = [
  "af", "Afrikaans";
  "agq", "Aghem";
  "ak", "Akan";
  "am", "አማርኛ";
  "ar", "العربية";
  "asa", "Kipare";
  "ast", "asturianu";
  "as", "অসমীয়া";
  "az", "azəri";
  "az_Cyrl", "азәрбајҹан";
  "bas", "Ɓàsàa";
  "bem", "Ichibemba";
  "be", "беларуская";
  "bez", "Hibena";
  "bg", "български";
  "bm", "bamanakan";
  "bn", "বাংলা";
  "bo", "བོད་སྐད་";
  "br", "brezhoneg";
  "brx", "बड़ो";
  "bs", "bosanski";
  "bs_Cyrl", "босански";
  "ca", "català";
  "ccp", "𑄌𑄋𑄴𑄟𑄳𑄦";
  "ceb", "Binisaya";
  "ce", "нохчийн";
  "cgg", "Rukiga";
  "chr", "ᏣᎳᎩ";
  "ckb", "کوردیی ناوەندی";
  "cs", "čeština";
  "cy", "Cymraeg";
  "dav", "Kitaita";
  "da", "dansk";
  "de", "Deutsch";
  "dje", "Zarmaciine";
  "doi", "डोगरी";
  "dsb", "dolnoserbšćina";
  "dua", "duálá";
  "dyo", "joola";
  "dz", "རྫོང་ཁ";
  "ebu", "Kĩembu";
  "ee", "Eʋegbe";
  "el", "Ελληνικά";
  "en", "English";
  "eo", "esperanto";
  "es", "español";
  "et", "eesti";
  "eu", "euskara";
  "ewo", "ewondo";
  "fa", "فارسی";
  "ff", "Pulaar";
  "ff_Adlm", "𞤆𞤵𞤤𞤢𞤪";
  "fil", "Filipino";
  "fi", "suomi";
  "fo", "føroyskt";
  "fr", "français";
  "fur", "furlan";
  "fy", "Frysk";
  "ga", "Gaeilge";
  "gd", "Gàidhlig";
  "gl", "galego";
  "gsw", "Schwiizertüütsch";
  "gu", "ગુજરાતી";
  "guz", "Ekegusii";
  "gv", "Gaelg";
  "haw", "ʻŌlelo Hawaiʻi";
  "ha", "Hausa";
  "he", "עברית";
  "hi", "हिन्दी";
  "hr", "hrvatski";
  "hsb", "hornjoserbšćina";
  "hu", "magyar";
  "hy", "հայերեն";
  "ia", "interlingua";
  "id", "bahasa Indonesia";
  "ig", "Igbo";
  "ii", "ꆈꌠꉙ";
  "is", "íslenska";
  "it", "italiano";
  "ja", "日本語";
  "jgo", "Ndaꞌa";
  "jmc", "Kimachame";
  "jv", "Jawa";
  "kab", "Taqbaylit";
  "kam", "Kikamba";
  "ka", "ქართული";
  "kde", "Chimakonde";
  "kea", "kabuverdianu";
  "khq", "Koyra ciini";
  "ki", "Gikuyu";
  "kkj", "kakɔ";
  "kk", "қазақ тілі";
  "kln", "Kalenjin";
  "kl", "kalaallisut";
  "km", "ខ្មែរ";
  "kn", "ಕನ್ನಡ";
  "kok", "कोंकणी";
  "ko", "한국어";
  "ksb", "Kishambaa";
  "ksf", "rikpa";
  "ksh", "Kölsch";
  "ks", "کٲشُر";
  "ku", "kurdî";
  "kw", "kernewek";
  "ky", "кыргызча";
  "lag", "Kɨlaangi";
  "lb", "Lëtzebuergesch";
  "lg", "Luganda";
  "lkt", "Lakȟólʼiyapi";
  "ln", "lingála";
  "lo", "ລາວ";
  "lrc", "لۊری شومالی";
  "lt", "lietuvių";
  "luo", "Dholuo";
  "lu", "Tshiluba";
  "luy", "Luluhia";
  "lv", "latviešu";
  "mai", "मैथिली";
  "mas", "Maa";
  "mer", "Kĩmĩrũ";
  "mfe", "kreol morisien";
  "mgh", "Makua";
  "mgo", "metaʼ";
  "mg", "Malagasy";
  "mi", "te reo Māori";
  "mk", "македонски";
  "ml", "മലയാളം";
  "mni", "মৈতৈলোন্";
  "mn", "монгол";
  "mr", "मराठी";
  "ms", "Melayu";
  "mt", "Malti";
  "mua", "MUNDAŊ";
  "my", "မြန်မာ";
  "mzn", "مازرونی";
  "naq", "Khoekhoegowab";
  "nb", "norsk bokmål";
  "nds", "Neddersass’sch";
  "nd", "isiNdebele";
  "ne", "नेपाली";
  "nl", "Nederlands";
  "nmg", "Kwasio";
  "nnh", "Shwóŋò ngiembɔɔn";
  "nn", "norsk nynorsk";
  "nus", "Thok Nath";
  "nyn", "Runyankore";
  "om", "Oromoo";
  "or", "ଓଡ଼ିଆ";
  "os", "ирон";
  "pa", "ਪੰਜਾਬੀ";
  "pa_Arab", "پنجابی";
  "pcm", "Naijíriá Píjin";
  "pl", "polski";
  "ps", "پښتو";
  "pt", "português";
  "qu", "Runasimi";
  "rm", "rumantsch";
  "rn", "Ikirundi";
  "rof", "Kihorombo";
  "ro", "română";
  "ru", "русский";
  "rwk", "Kiruwa";
  "rw", "Kinyarwanda";
  "sah", "саха тыла";
  "saq", "Kisampur";
  "sat", "ᱥᱟᱱᱛᱟᱲᱤ";
  "sa", "संस्कृत भाषा";
  "sbp", "Ishisangu";
  "sd", "سنڌي";
  "sd_Deva", "सिन्धी";
  "seh", "sena";
  "ses", "Koyraboro senni";
  "se", "davvisámegiella";
  "sg", "Sängö";
  "shi", "ⵜⴰⵛⵍⵃⵉⵜ";
  "shi_Latn", "Tashelḥiyt";
  "si", "සිංහල";
  "sk", "slovenčina";
  "sl", "slovenščina";
  "smn", "anarâškielâ";
  "sn", "chiShona";
  "so", "Soomaali";
  "sq", "shqip";
  "sr", "српски";
  "sr_Latn", "srpski";
  "su", "Basa Sunda";
  "sv", "svenska";
  "sw", "Kiswahili";
  "ta", "தமிழ்";
  "teo", "Kiteso";
  "te", "తెలుగు";
  "tg", "тоҷикӣ";
  "th", "ไทย";
  "ti", "ትግር";
  "tk", "türkmen dili";
  "to", "lea fakatonga";
  "tr", "Türkçe";
  "tt", "татар";
  "twq", "Tasawaq senni";
  "tzm", "Tamaziɣt n laṭlaṣ";
  "ug", "ئۇيغۇرچە";
  "uk", "українська";
  "ur", "اردو";
  "uz", "o‘zbek";
  "vai", "ꕙꔤ";
  "vi", "Tiếng Việt";
  "vun", "Kyivunjo";
  "wae", "Walser";
  "wo", "Wolof";
  "xh", "isiXhosa";
  "xog", "Olusoga";
  "yav", "nuasue";
  "yi", "ייִדיש";
  "yo", "Èdè Yorùbá";
  "yue", "中文 (粵語)";
  "zgh", "ⵜⴰⵎⴰⵣⵉⵖⵜ";
  "zh", "普通话";
  "zu", "isiZulu";
]
